export const homePageKeywords =
  "Private jet hire, private jet rental, luxury jet charter, corporate jet charter, business jet hire, private plane rental, executive jet charter, private aircraft charter, private flight services, charter private aircraft, luxury private flights, VIP jet charter, jet hire services, personal jet charter, exclusive jet rental, charter jet services, private aviation services, jet charter companies, private air travel, premium jet charter, charter a private jet, private jet booking, luxury air charter, bespoke jet charter, private jet services, charter jet flights, private jet hire cost, business aviation charter, private jet flight hire, high-end jet charter, private jet hire UK, luxury plane charter, private jet rental prices, chartered jet services, VIP air charter, luxury jet hire, private plane charter, business jet charter services, private jet flight rental, corporate air charter, private jet travel, exclusive air charter, private air hire, private jet companies, luxury air travel, private aircraft hire, executive air charter, personal jet hire, VIP aircraft charter, bespoke air charter, private jet hire services, charter private jets, luxury private air travel, private jet hire companies, business jet rental, private jet leasing, private jet hire London, jet charter services, executive jet rental, private aircraft rental, luxury air hire, charter air services, private air charter, premium private jets, VIP jet rental, exclusive jet hire, private aviation charter, private jet flights, luxury jet travel, business air charter, high-end private jets, chartered private jets, private jet travel services, bespoke private jets, corporate jet rental, private jet hire prices, private jet companies UK, exclusive air hire, private aircraft charter services, luxury private jets, VIP private jet charter, corporate jet hire, private air rental, luxury jet services, private jet cost, executive jet hire, private jet rental companies, private plane hire, luxury private jet charter, private jet service providers, jet charter solutions";

export const fleetPageKeywords = [
  "private jet charter",
  "private jet rental",
  "private jet cost",
  "empty leg flights",
  "private jet membership",
  "private jet brands",
  "fastest private jets",
  "most luxurious private jets",
  "private jet for business",
  "private jet for vacation",
  "private jet to Europe",
  "private jet to Asia",
  "private jet to Middle East",
  "private jet to Africa",
  "private jet insurance",
  "private jet maintenance",
  "private jet financing",
  "fractional jet ownership",
  "jet card programs",
  "private jet safety",
  "private jet catering",
  "private jet amenities",
  "Swiftwings private jet charter",
  "Swiftwings private jet rental",
  "Swiftwings private jet cost",
  "Swiftwings empty leg flights",
  "Swiftwings jet card program",
  "Swiftwings vs. Flexjet",
  "Swiftwings vs. NetJets",
  "Swiftwings vs. XOJet",
  "Swiftwings reviews",
  "Swiftwings safety record",
  "Swiftwings customer service",
  "Bombardier Challenger 604 private jet",
  "Bombardier Global 6000 private jet",
  "Embraer Legacy 600 private jet",
  "Hawker 850xp private jet",
  "Learjet private jet",
  "Hawker Hs25 private jet",
  "Gulfstream G650 private jet",
  "Gulfstream G450 private jet",
  "private jet with most legroom",
  "private jet with longest range",
  "private jet with best wifi",
  "private jet for short haul flights",
  "private jet for long haul flights",
  "private jet for group travel",
  "private jet for corporate travel",
  "private jet for weekend getaway",
  "private jet for special occasions",
  "private jet for medical transport",
  "private jet cargo service",
  "private jet catering options",
  "private jet in-flight entertainment",
  "private jet ground transportation",
  "private jet charter Lagos",
  "private jet rental Lagos",
  "private jet from Lagos to Dubai",
  "private jet from Lagos to London",
  "private jet from Lagos to New York",
  "private jet to private airports Lagos",
  "private jet maintenance facilities Lagos",
  "best private jet companies",
  "cheapest private jet charter",
  "fastest private jet charter",
  "most luxurious private jet charter",
  "private jet vs. first class",
  "private jet ownership vs. charter",
  "renting a private jet vs. commercial flights",
  "private jet for 4 passengers",
  "private jet for 10 passengers",
  "private jet for 20 passengers",
  "private aviation",
  "business aviation",
  "executive jets",
  "luxury travel",
  "VIP travel",
  "on-demand flights",
  "private jet app",
  "private jet booking",
  "private jet terminal",
  "charter flights",
  "private air charters",
  "private aircraft charter",
  "private jet aircraft",
  "nigeria airport",
  "plane and jet",
  "airplanes and jets",
  "name of international airport in nigeria",
  "private planes",
  "charter aircraft",
  "private charter planes",
  "private planes cost",
  "private air charters",
  "private jet charter flights",
  "private jet from lagos to abuja price",
  "private aircraft charter",
  "private airplane charters",
  "private jet price nigeria",
  "private jet aircraft",
  "business jet cost",
  "airplane private jet",
  "luxury private airplanes",
  "prices of private jet in nigeria",
  "private air charter",
].join(", ");

export const destinationsPageKeywords = [
  "private jet charter",
  "private jet rental",
  "private jet cost",
  "empty leg flights",
  "private jet membership",
  "luxury private jet travel",
  "most popular private jet destinations",
  "private jet for business",
  "private jet for vacation",
  "private jet to Europe",
  "private jet to Asia",
  "private jet to Caribbean",
  "private jet to Middle East",
  "private jet destinations in North America",
  "private jet destinations in Europe",
  "private jet destinations in Asia",
  "private jet destinations in Africa",
  "private jet destinations in South America",
  "private jet destinations in the Caribbean",
  "private jet destinations in the Mediterranean",
  "private jet to Aspen",
  "private jet to Dubai",
  "private jet to Bahamas",
  "private jet to Ibiza",
  "private jet to French Riviera",
  "private jet to Maldives",
  "private jet to St. Barts",
  "private jet to Necker Island",
  "private jet to Monaco",
  "private jet to Mustique",
  "Swiftwings private jet destinations",
  "Swiftwings private jet charter to South Africa",
  "Swiftwings private jet empty legs",
  "Swiftwings private jet membership benefits",
  "compare Swiftwings to Vistajet",
  "Swiftwings private jet reviews",
  "is Swiftwings jet charter safe?",
  "fastest private jet to Kenya",
  "most private jet friendly airports in Nigeria",
  "best private jet experiences",
  "private jet for weekend getaway",
  "private jet honeymoon destinations",
  "romantic private jet getaways",
  "private jet for family vacation",
  "adventure private jet tours",
  "skiing by private jet",
  "golfing by private jet",
  "glamping by private jet",
  "private jet aviation companies",
  "private jet benefits vs commercial",
  "private jet safety regulations",
  "Swiftwings jet charter for business travel",
  "Swiftwings private jet catering options",
  "Swiftwings jet in-flight entertainment",
  "Swiftwings jet security protocols",
  "charter flights",
  "private air charters",
  "private aircraft charter",
  "private jet aircraft",
  "nigeria airport",
  "plane and jet",
  "airplanes and jets",
  "name of international airport in nigeria",
  "private planes",
  "charter aircraft",
  "private charter planes",
  "private planes cost",
  "private air charters",
  "private jet charter flights",
  "private jet from lagos to abuja price",
  "private aircraft charter",
  "private airplane charters",
  "private jet price nigeria",
  "private jet aircraft",
  "business jet cost",
  "airplane private jet",
  "luxury private airplanes",
  "prices of private jet in nigeria",
  "private air charter",
].join(", ");

export const servicesPageKeywords = [
  "Swiftwings private jet charter",
  "private jet rental Swiftwings",
  "Swiftwings private jet cost",
  "empty leg flights Swiftwings",
  "Swiftwings private jet membership",
  "hourly rate private jet Swiftwings",
  "types of private jets Swiftwings",
  "Swiftwings private jet to Europe",
  "Swiftwings private jet to Asia",
  "Swiftwings private jet to Middle East",
  "Swiftwings private jet for vacation",
  "Swiftwings private jet for business",
  "Swiftwings private jet for wedding",
  "Swiftwings private jet for group travel",
  "Swiftwings private jet catering",
  "Swiftwings private jet in-flight entertainment",
  "most popular private jet models Swiftwings",
  "benefits of private jet travel Swiftwings",
  "compare private jet companies to Swiftwings",
  "Swiftwings private jet vs commercial airlines",
  "Swiftwings private jet reviews",
  "Swiftwings customer service",
  "Swiftwings private jet safety",
  "Swiftwings private jet insurance",
  "how to book a private jet Swiftwings",
  "Swiftwings private jet contact information",
  "Swiftwings jet membership programs",
  "features of Swiftwings private jets",
  "Swiftwings private jet destinations",
  "Swiftwings private jet empty leg deals",
  "luxury private jet travel Swiftwings",
  "Swiftwings private jet for celebrities",
  "how much does it cost to rent a private jet Swiftwings",
  "Swiftwings private jet for short notice travel",
  "Swiftwings private jet for international travel",
  "Swiftwings private jet for weekend getaway",
  "book private jet online Swiftwings",
  "last minute private jet flights Swiftwings",
  "Swiftwings private jet quotes",
  "Swiftwings private jet for corporate travel",
  "Swiftwings private jet for sports teams",
  "Swiftwings private jet for music tours",
  "Swiftwings private jet for film production",
  "Swiftwings private jet for medical transport",
  "Swiftwings private jet for cargo transport",
  "Swiftwings private jet for pets",
  "Swiftwings private jet for disaster relief",
  "Swiftwings private jet sustainability",
  "is private jet travel safe",
  "Swiftwings private jet pilot qualifications",
  "history of Swiftwings private jet company",
  "future of private jet travel",
  "swiftwings helicopters",
  "swiftwings helicopter flight",
].join(", ");

export const aboutUsPageKeywords = [
  "Swiftwings",
  "Swiftwingsjet",
  "Swift",
  "Swiftjet",
  "About Swiftwings",
  "About Swiftwingsjet",
  "About Swift",
  "charter flights",
  "private air charters",
  "private aircraft charter",
  "private jet aircraft",
  "nigeria airport",
  "plane and jet",
  "airplanes and jets",
  "name of international airport in nigeria",
  "private planes",
  "charter aircraft",
  "private charter planes",
  "private planes cost",
  "private air charters",
  "private jet charter flights",
  "private jet from lagos to abuja price",
  "private aircraft charter",
  "private airplane charters",
  "private jet price nigeria",
  "private jet aircraft",
  "business jet cost",
  "airplane private jet",
  "luxury private airplanes",
  "prices of private jet in nigeria",
  "private air charter",
  "private jet charter",
  "private jet rental",
  "private jet cost",
  "private jet membership",
  "empty leg flights",
  "private jet benefits",
  "how to charter a private jet",
  "types of private jets",
  "private jet companies",
  "private jet comparison",
  "luxury travel",
  "luxury vacation",
  "business travel",
  "VIP travel",
  "exclusive travel",
  "first class travel",
  "executive travel",
  "bespoke travel",
  "worldwide travel",
  "global travel",
  "private jet safety",
  "private jet security",
  "private jet regulations",
  "private jet maintenance",
  "private jet insurance",
  "accredited private jet companies",
  "on-demand private jets",
  "private jet crew",
  "private jet pilots",
  "Swiftwings private jet",
  "Swiftwings charter",
  "Swiftwings membership",
  "Swiftwings destinations",
  "Swiftwings reviews",
  "Swiftwings safety",
  "Swiftwings experience",
  "Swiftwings contact",
  "Swiftwings for business",
  "Swiftwings for families",
  "private jet charter Lagos",
  "private jet rental near me",
  "private jet flights from Abuja",
  "empty leg flights Lagos to Abuja",
  "how much does it cost to charter a private jet for a weekend getaway",
  "best private jet companies for international travel",
  "most luxurious private jet interiors",
  "fastest private jets for transatlantic flights",
  "booking a private jet last minute",
  "benefits of private jet travel",
  "advantages of private jet charter",
  "is private jet ownership worth it",
  "private jet vs commercial airlines",
  "what to expect on a private jet flight",
].join(", ");
