"use client";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { BrowserRouter } from "react-router-dom"; // Import BrowserRouter
import { store } from "@/redux/store";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

const metadata = {
  title: "Swift wings jet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <BrowserRouter> 
        <html lang="en">
          <body className={poppins.className}>{children}</body>
        </html>
      </BrowserRouter>
    </Provider>
  );
}